// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"envmn/config"
	"envmn/internal/api"
	"envmn/internal/api/grpc"
	"envmn/internal/infrastructure"
	"envmn/internal/metircs"
	"envmn/internal/repository"
	"envmn/internal/service"
	"envmn/logs"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/redis/go-redis/v9"
	"golang.org/x/sync/errgroup"
	"net"
	"net/http"
)

// Injectors from bootstrap.go:

// Wire injector function
func InitializeApp(cfg config.StartupConfig) (*App, error) {
	logger := provideRootLogger()
	cacheLogger := provideCacheLogs(logger)
	redisConfig := cfg.Redis
	repositoryCacheRedis, err := provideRepositoryCacheRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	cacheConfig := cfg.Cache
	cacheTTL := provideCacheTTL(cacheConfig)
	metricsRepositoryCacheMetricsName := provideMetricsName()
	repositoryMetrics, err := metrics.ProvideRepositoryCacheMetrics(metricsRepositoryCacheMetricsName)
	if err != nil {
		return nil, err
	}
	redisCacheSettings := repository.ProvideRedisCacheSettings(repositoryCacheRedis, cacheTTL, repositoryMetrics)
	postgresDBConfig := cfg.DB
	pool, err := providePostgresDB(postgresDBConfig)
	if err != nil {
		return nil, err
	}
	environmentRepositories := repository.ProvideEnvironmentRepositories(pool)
	environmentRepository := repository.ProvideCachedEnvironmentRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	environmentVariablesRepository := repository.ProvideCachedEnvironmentVariablesRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	reservedEnvironmentsStorage := infrastructure.ProvideReservedEnvironmentsStorage()
	publisher := providePublisher()
	accessPolicyRepositories := repository.ProvideAccessPolicyRepositories(pool)
	accessPolicyFinderSaver := repository.ProvideCachedAccessPolicyFinderSaver(cacheLogger, redisCacheSettings, accessPolicyRepositories)
	secretKeysConfig := cfg.Keys
	keySeed, err := provideKeyGenSeed(secretKeysConfig)
	if err != nil {
		return nil, err
	}
	keyGenerator := infrastructure.ProvideKeyGenerator(keySeed)
	accessControl := provideAccessControlService(accessPolicyFinderSaver, keyGenerator)
	bootstrapNotifiersRedis, err := provideNotifiersRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	bootstrapNotifiersRetrierLogger := provideNotifiersRetrierLogger(logger)
	notifiersConfig := cfg.Notifiers
	retry := provideNotifiersRetrier(bootstrapNotifiersRetrierLogger, notifiersConfig)
	notifierSettings := provideNotifierSettings(bootstrapNotifiersRedis, logger, retry)
	notifier := infrastructure.ProvideNotifier(notifierSettings)
	clientKeyGenerator := infrastructure.ProvideClientKeyGenerator(keySeed)
	distributionDependincies := provideClientDependincies(environmentRepository, environmentVariablesRepository, reservedEnvironmentsStorage, publisher, accessControl, notifier, clientKeyGenerator)
	distributionServices := service.ProvideDistributionServices(distributionDependincies)
	environmentPoliciesRepository := repository.ProvideCachedEnvironmentPoliciesRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	accessPolicyRepository := repository.ProvideCachedAccessPolicyRepository(cacheLogger, redisCacheSettings, accessPolicyRepositories)
	managmentDependincies := provideManagmentDependincies(environmentRepository, environmentPoliciesRepository, environmentVariablesRepository, accessPolicyRepository, reservedEnvironmentsStorage, accessControl, publisher)
	managementServices := service.ProvideManagementServices(managmentDependincies)
	certificateConfig := cfg.Certificate
	settigns, err := provideGRPCServerSettings(logger, certificateConfig)
	if err != nil {
		return nil, err
	}
	server := api.ProvideGRPCServer(distributionServices, managementServices, settigns)
	bootstrapGRPCServerConfig := provideGRPCServerConf(cfg)
	bootstrapHttpServerConfig := provideHTTPServerConf(cfg)
	app := newApp(server, pool, repositoryCacheRedis, bootstrapNotifiersRedis, logger, bootstrapGRPCServerConfig, bootstrapHttpServerConfig)
	return app, nil
}

// bootstrap.go:

type (
	httpServerConfig config.ServerConfig
	gRPCServerConfig config.ServerConfig
)

type App struct {
	grpcServer     *grpc.Server
	httpServer     *http.Server
	db             *pgxpool.Pool
	cacheRedis     *redis.Client
	notifiersRedis *redis.Client
	log            logs.Logger
	grpcServerConf config.ServerConfig
	httpServerConf config.ServerConfig
}

func newApp(
	grpcServer *grpc.Server,
	db *pgxpool.Pool,
	cacheRedis repository.RepositoryCacheRedis, notifiersRedis2 notifiersRedis,
	log logs.Logger,
	grpcServerConf gRPCServerConfig,
	httpServerConf httpServerConfig,
) *App {
	return &App{
		grpcServer:     grpcServer,
		db:             db,
		cacheRedis:     (*redis.Client)(cacheRedis),
		notifiersRedis: (*redis.Client)(notifiersRedis2),
		log:            log,
		grpcServerConf: config.ServerConfig(grpcServerConf),
		httpServerConf: config.ServerConfig(httpServerConf),
	}
}

func (app *App) shutdown(ctx context.Context) error {
	app.grpcServer.GracefulStop()
	if err := app.httpServer.Shutdown(ctx); err != nil {
		app.log.Error("HTTP server graceful shutdown failed: %v", logs.Args{"error": err})
	}
	app.db.Close()
	app.cacheRedis.Close()
	app.notifiersRedis.Close()
	return nil
}

func (app *App) Run() func(context.Context) error {
	go func() {
		var g errgroup.Group

		g.Go(app.runGRPC)
		g.Go(app.runHTTP)

		if err := g.Wait(); err != nil {
			app.log.Error("Application failed", logs.Args{"error": err})
		}
	}()
	return app.shutdown
}

func (app *App) runGRPC() error {
	addr := app.grpcServerConf.Addr()
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("failed to listen: %w", err)
	}

	if err = app.grpcServer.Serve(lis); err != nil {
		return fmt.Errorf("grpc server failed: %w", err)
	}
	return nil
}

func (app *App) runHTTP() error {
	addr := app.httpServerConf.Addr()

	app.httpServer = &http.Server{
		Addr:    addr,
		Handler: promhttp.Handler(),
	}
	fmt.Printf("Server prometheus metrics server on %s...\n", addr)
	if err := app.httpServer.ListenAndServe(); err != nil {
		return fmt.Errorf("http server failed: %w", err)
	}
	return nil
}

func Build(cfg config.StartupConfig) (*App, error) {
	app, err := InitializeApp(cfg)
	if err != nil {
		return nil, err
	}
	return app, nil
}
