// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"envmn/config"
	"envmn/internal/api/grpc"
	"envmn/internal/infrastructure"
	"envmn/internal/metircs"
	"envmn/internal/repository"
	"envmn/internal/service"
	"envmn/logs"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"net"
)

// Injectors from bootstrap.go:

// Wire injector function
func InitializeApp(cfg config.StartupConfig) (*App, error) {
	logger := provideRootLogger()
	cacheLogger := provideCacheLogs(logger)
	redisConfig := cfg.Redis
	repositoryCacheRedis, err := provideRepositoryCacheRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	cacheConfig := cfg.Cache
	cacheTTL := provideCacheTTL(cacheConfig)
	metricsRepositoryCacheMetricsName := provideMetricsName()
	repositoryMetrics, err := metrics.ProvideRepositoryCacheMetrics(metricsRepositoryCacheMetricsName)
	if err != nil {
		return nil, err
	}
	redisCacheSettings := repository.ProvideRedisCacheSettings(repositoryCacheRedis, cacheTTL, repositoryMetrics)
	postgresDBConfig := cfg.DB
	pool, err := providePostgresDB(postgresDBConfig)
	if err != nil {
		return nil, err
	}
	environmentRepositories := repository.ProvideEnvironmentRepositories(pool)
	environmentRepository := repository.ProvideCachedEnvironmentRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	environmentVariablesRepository := repository.ProvideCachedEnvironmentVariablesRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	reservedEnvironmentsStorage := infrastructure.ProvideReservedEnvironmentsStorage()
	eventPublisher := provideEventPublisher()
	accessPolicyRepositories := repository.ProvideAccessPolicyRepositories(pool)
	accessPolicyFinderSaver := repository.ProvideCachedAccessPolicyFinderSaver(cacheLogger, redisCacheSettings, accessPolicyRepositories)
	secretKeysConfig := cfg.Keys
	keySeed, err := provideKeyGenSeed(secretKeysConfig)
	if err != nil {
		return nil, err
	}
	keyGenerator := infrastructure.ProvideKeyGenerator(keySeed)
	accessControlService := provideAccessControlService(accessPolicyFinderSaver, keyGenerator)
	bootstrapNotifiersRedis, err := provideNotifiersRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	bootstrapNotifiersRetrierLogger := provideNotifiersRetrierLogger(logger)
	notifiersConfig := cfg.Notifiers
	retry := provideNotifiersRetrier(bootstrapNotifiersRetrierLogger, notifiersConfig)
	notifierSettings := provideNotifierSettings(bootstrapNotifiersRedis, logger, retry)
	notifier := infrastructure.ProvideNotifier(notifierSettings)
	clientKeyGenerator := infrastructure.ProvideClientKeyGenerator(keySeed)
	clientDependincies := provideClientDependincies(environmentRepository, environmentVariablesRepository, reservedEnvironmentsStorage, eventPublisher, accessControlService, notifier, clientKeyGenerator)
	client := service.ProvideClient(clientDependincies)
	environmentPoliciesRepository := repository.ProvideCachedEnvironmentPoliciesRepository(cacheLogger, redisCacheSettings, environmentRepositories)
	accessPolicyRepository := repository.ProvideCachedAccessPolicyRepository(cacheLogger, redisCacheSettings, accessPolicyRepositories)
	managmentDependincies := provideManagmentDependincies(environmentRepository, environmentPoliciesRepository, environmentVariablesRepository, accessPolicyRepository, reservedEnvironmentsStorage, accessControlService, eventPublisher)
	management := service.ProvideManagement(managmentDependincies)
	certificateConfig := cfg.Certificate
	serverSettigns, err := provideServerSettings(logger, certificateConfig)
	if err != nil {
		return nil, err
	}
	server, err := provideGrpcServer(client, management, serverSettigns)
	if err != nil {
		return nil, err
	}
	serverConfig := cfg.Server
	app := newApp(server, pool, repositoryCacheRedis, bootstrapNotifiersRedis, logger, serverConfig)
	return app, nil
}

// bootstrap.go:

type App struct {
	grpcServer     *grpc.Server
	db             *pgxpool.Pool
	cacheRedis     *redis.Client
	notifiersRedis *redis.Client
	logger         logs.Logger
	serverConf     config.ServerConfig
}

func newApp(
	grpcServer *grpc.Server,
	db *pgxpool.Pool,
	cacheRedis repository.RepositoryCacheRedis, notifiersRedis2 notifiersRedis,
	logger logs.Logger,
	cfg config.ServerConfig,
) *App {
	return &App{
		grpcServer:     grpcServer,
		db:             db,
		cacheRedis:     (*redis.Client)(cacheRedis),
		notifiersRedis: (*redis.Client)(notifiersRedis2),
		logger:         logger,
		serverConf:     cfg,
	}
}

func (a *App) shutdown(ctx context.Context) error {
	a.grpcServer.GracefulStop()
	a.db.Close()
	a.cacheRedis.Close()
	a.notifiersRedis.Close()
	return nil
}

func (a *App) Run() func(ctx context.Context) error {
	go func() {
		addr := fmt.Sprintf("%s:%d", a.serverConf.Host, a.serverConf.Port)
		lis, err := net.Listen("tcp", addr)
		if err != nil {
			a.logger.Error("Failed to listen", logs.Args{"error": err})
			return
		}
		if err := a.grpcServer.Serve(lis); err != nil {
			a.logger.Error("Failed to serve", logs.Args{"error": err})
		}
	}()
	return a.shutdown
}

func Build(cfg config.StartupConfig) (*App, error) {
	app, err := InitializeApp(cfg)
	if err != nil {
		return nil, err
	}
	return app, nil
}
