// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type AccessPolicy struct {
	ID        uuid.UUID `db:"id"`
	Name      string    `db:"name"`
	Key       string    `db:"key"`
	CreatedAt time.Time `db:"created_at"`
}

type Environment struct {
	ID                  uuid.UUID `db:"id"`
	Name                string    `db:"name"`
	Description         *string   `db:"description"`
	LastVariablesUpdate time.Time `db:"last_variables_update"`
	CreatedAt           time.Time `db:"created_at"`
}

type EnvironmentsAccessPolicy struct {
	AccessPolicyID    uuid.UUID `db:"access_policy_id"`
	EnvironmentID     uuid.UUID `db:"environment_id"`
	ChangesPermission bool      `db:"changes_permission"`
}

type Variable struct {
	ID            int32     `db:"id"`
	Key           string    `db:"key"`
	Value         string    `db:"value"`
	EnvironmentID uuid.UUID `db:"environment_id"`
	CreatedAt     time.Time `db:"created_at"`
}
