// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addPolicyToEnvironment = `-- name: AddPolicyToEnvironment :exec
INSERT INTO environments_access_policies (environment_id, access_policy_id, changes_allowed)
VALUES ($1, $2, $3)
`

type AddPolicyToEnvironmentParams struct {
	EnvironmentID  uuid.UUID `db:"environment_id"`
	AccessPolicyID uuid.UUID `db:"access_policy_id"`
	ChangesAllowed bool      `db:"changes_allowed"`
}

func (q *Queries) AddPolicyToEnvironment(ctx context.Context, arg AddPolicyToEnvironmentParams) error {
	_, err := q.db.Exec(ctx, addPolicyToEnvironment, arg.EnvironmentID, arg.AccessPolicyID, arg.ChangesAllowed)
	return err
}

const createPolicy = `-- name: CreatePolicy :exec
INSERT INTO access_policies (id, name, key)
VALUES ($1, $2, $3)
`

type CreatePolicyParams struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
	Key  string    `db:"key"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) error {
	_, err := q.db.Exec(ctx, createPolicy, arg.ID, arg.Name, arg.Key)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM access_policies
WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const deletePolicyFromEnvironment = `-- name: DeletePolicyFromEnvironment :exec
DELETE FROM environments_access_policies
WHERE environment_id = $1 AND access_policy_id = $2
`

type DeletePolicyFromEnvironmentParams struct {
	EnvironmentID  uuid.UUID `db:"environment_id"`
	AccessPolicyID uuid.UUID `db:"access_policy_id"`
}

func (q *Queries) DeletePolicyFromEnvironment(ctx context.Context, arg DeletePolicyFromEnvironmentParams) error {
	_, err := q.db.Exec(ctx, deletePolicyFromEnvironment, arg.EnvironmentID, arg.AccessPolicyID)
	return err
}

const findPolicyByID = `-- name: FindPolicyByID :one
SELECT id, name, key 
FROM access_policies 
WHERE id = $1
`

type FindPolicyByIDRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
	Key  string    `db:"key"`
}

func (q *Queries) FindPolicyByID(ctx context.Context, id uuid.UUID) (FindPolicyByIDRow, error) {
	row := q.db.QueryRow(ctx, findPolicyByID, id)
	var i FindPolicyByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Key)
	return i, err
}

const findPolicyByKey = `-- name: FindPolicyByKey :one
SELECT id, name, key 
FROM access_policies 
WHERE key = $1
`

type FindPolicyByKeyRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
	Key  string    `db:"key"`
}

func (q *Queries) FindPolicyByKey(ctx context.Context, key string) (FindPolicyByKeyRow, error) {
	row := q.db.QueryRow(ctx, findPolicyByKey, key)
	var i FindPolicyByKeyRow
	err := row.Scan(&i.ID, &i.Name, &i.Key)
	return i, err
}

const findPolicyByName = `-- name: FindPolicyByName :one
SELECT id, name, key 
FROM access_policies 
WHERE name = $1
`

type FindPolicyByNameRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
	Key  string    `db:"key"`
}

func (q *Queries) FindPolicyByName(ctx context.Context, name string) (FindPolicyByNameRow, error) {
	row := q.db.QueryRow(ctx, findPolicyByName, name)
	var i FindPolicyByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.Key)
	return i, err
}

const getPoliciesByEnv = `-- name: GetPoliciesByEnv :many
SELECT p.id, p.name, p.key, ep.changes_allowed
FROM environments_access_policies ep
JOIN access_policies p ON p.id = ep.access_policy_id
WHERE ep.environment_id = $1
`

type GetPoliciesByEnvRow struct {
	ID             uuid.UUID `db:"id"`
	Name           string    `db:"name"`
	Key            string    `db:"key"`
	ChangesAllowed bool      `db:"changes_allowed"`
}

func (q *Queries) GetPoliciesByEnv(ctx context.Context, environmentID uuid.UUID) ([]GetPoliciesByEnvRow, error) {
	rows, err := q.db.Query(ctx, getPoliciesByEnv, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPoliciesByEnvRow
	for rows.Next() {
		var i GetPoliciesByEnvRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.ChangesAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
