// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variables.sql

package queries

import (
	"context"

	"envmn/internal/repository/postgres/dbtypes"
	"github.com/google/uuid"
)

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM variables WHERE environment_id = $1 AND key = $2
`

type DeleteVariableParams struct {
	EnvironmentID uuid.UUID `db:"environment_id"`
	Key           string    `db:"key"`
}

func (q *Queries) DeleteVariable(ctx context.Context, arg DeleteVariableParams) error {
	_, err := q.db.Exec(ctx, deleteVariable, arg.EnvironmentID, arg.Key)
	return err
}

const getVariablesByEnv = `-- name: GetVariablesByEnv :many
SELECT key, value FROM variables WHERE environment_id = $1
`

type GetVariablesByEnvRow struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

func (q *Queries) GetVariablesByEnv(ctx context.Context, environmentID uuid.UUID) ([]GetVariablesByEnvRow, error) {
	rows, err := q.db.Query(ctx, getVariablesByEnv, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariablesByEnvRow
	for rows.Next() {
		var i GetVariablesByEnvRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVariables = `-- name: UpsertVariables :exec
INSERT INTO variables (key, value, environment_id)
SELECT
  u.key,
  u.value,
  u.environment_id
FROM UNNEST($1::variable_entry[])
AS u(key, value, environment_id)
ON CONFLICT (key, environment_id)
DO UPDATE SET value = EXCLUDED.value
`

func (q *Queries) UpsertVariables(ctx context.Context, dollar_1 []dbtypes.VariableEntry) error {
	_, err := q.db.Exec(ctx, upsertVariables, dollar_1)
	return err
}
