syntax = "proto3";

package envmn.management;

option go_package = "api/proto;proto";

import "google/protobuf/empty.proto";

service ManagementService {
  // all requests require x-admin-password metadata
  rpc CreateEnvironment(CreateEnvironmentRequest) returns (CreateEnvironmentResponse);
  rpc GetAllEnvironments(GetAllEnvironmentsRequest) returns (GetAllEnvironmentsResponse);
  rpc GetEnvironment(GetEnvironmentRequest) returns (GetEnvironmentResponse);
  rpc DeleteEnvironment(DeleteEnvironmentRequest) returns (google.protobuf.Empty);
  rpc UpdateEnvironmentInfo(UpdateEnvironmentInfoRequest) returns (google.protobuf.Empty);

  rpc CreateAccessPolicy(CreateAccessPolicyRequest) returns (CreateAccessPolicyResponse);
 	rpc ListPolicyEnvironments(ListPolicyEnvironmentsRequest) returns (ListPolicyEnvironmentsResponse);
  rpc GetPolicyByName(GetPolicyByNameRequest) returns (GetPolicyByNameResponse);
  rpc RemovePolicy(RemovePolicyRequest) returns (google.protobuf.Empty);
  rpc AddPolicyToEnvironment(AddPolicyToEnvironmentRequest) returns (google.protobuf.Empty);
  rpc RemovePolicyFromEnvironment(RemovePolicyFromEnvironmentRequest) returns (google.protobuf.Empty);

  rpc UpdateEnvironmentVariables(UpdateEnvironmentVariablesRequest) returns (google.protobuf.Empty);
  rpc RemoveVariableFromEnvironment(RemoveVariableFromEnvironmentRequest) returns (google.protobuf.Empty);
}

message Environment {
  string name = 1;
  map<string, string> variables = 2;
  string description = 3;
  bool reserved = 4;
}

message PolicyEnvironmentsItem {
	string environment_name = 1;
	bool changes_permission = 2;
}

message CreateEnvironmentRequest {
  string name = 1;
  optional string description = 2;
  map<string, string> variables = 3;
}

message CreateEnvironmentResponse {
  string id = 1;
}

message GetAllEnvironmentsRequest {
  bool reserved = 1;
}

message GetAllEnvironmentsResponse {
  repeated Environment environments = 1;
}

message GetEnvironmentRequest {
  string name = 1;
}

message GetEnvironmentResponse {
  Environment environment = 1;
}

message DeleteEnvironmentRequest {
  string name = 1;
}

message UpdateEnvironmentInfoRequest {
  string old_name = 1;
  optional string new_name = 2;
  optional string description = 3;
}

message CreateAccessPolicyRequest {
  string name = 1;
  string key = 2;
}

message CreateAccessPolicyResponse {
  string id = 1;
}

message ListPolicyEnvironmentsRequest {
  string policy_id = 1;
}

message ListPolicyEnvironmentsResponse {
  repeated PolicyEnvironmentsItem items = 1;
}

message GetPolicyByNameRequest {
  string name = 1;
}

message GetPolicyByNameResponse {
  string id = 1;
  string name = 2;
  string key = 3;
}

message RemovePolicyRequest {
  string id = 1;
}

message AddPolicyToEnvironmentRequest {
  string environment_name = 1;
  string policy_id = 2;
  bool changes_permission = 3;
}

message RemovePolicyFromEnvironmentRequest {
  string environment_name = 1;
  string policy_id = 2;
}

message UpdateEnvironmentVariablesRequest {
  string environment_name = 1;
  map<string, string> variables = 2;
  optional string access_key = 3;
}

message RemoveVariableFromEnvironmentRequest {
  string environment_name = 1;
  string variable_key = 2;
}

