// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientService_GetClientVariables_FullMethodName = "/envmn.ClientService/GetClientVariables"
	ClientService_UpdateVariables_FullMethodName    = "/envmn.ClientService/UpdateVariables"
	ClientService_SubscribeOnUpdates_FullMethodName = "/envmn.ClientService/SubscribeOnUpdates"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	GetClientVariables(ctx context.Context, in *GetClientVariablesRequest, opts ...grpc.CallOption) (*GetClientVariablesResponse, error)
	UpdateVariables(ctx context.Context, in *UpdateVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SubscribeOnUpdates(ctx context.Context, in *SubscribeOnUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeOnUpdatesResponse], error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) GetClientVariables(ctx context.Context, in *GetClientVariablesRequest, opts ...grpc.CallOption) (*GetClientVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientVariablesResponse)
	err := c.cc.Invoke(ctx, ClientService_GetClientVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateVariables(ctx context.Context, in *UpdateVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientService_UpdateVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) SubscribeOnUpdates(ctx context.Context, in *SubscribeOnUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeOnUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[0], ClientService_SubscribeOnUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeOnUpdatesRequest, SubscribeOnUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SubscribeOnUpdatesClient = grpc.ServerStreamingClient[SubscribeOnUpdatesResponse]

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	GetClientVariables(context.Context, *GetClientVariablesRequest) (*GetClientVariablesResponse, error)
	UpdateVariables(context.Context, *UpdateVariablesRequest) (*emptypb.Empty, error)
	SubscribeOnUpdates(*SubscribeOnUpdatesRequest, grpc.ServerStreamingServer[SubscribeOnUpdatesResponse]) error
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) GetClientVariables(context.Context, *GetClientVariablesRequest) (*GetClientVariablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientVariables not implemented")
}
func (UnimplementedClientServiceServer) UpdateVariables(context.Context, *UpdateVariablesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVariables not implemented")
}
func (UnimplementedClientServiceServer) SubscribeOnUpdates(*SubscribeOnUpdatesRequest, grpc.ServerStreamingServer[SubscribeOnUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeOnUpdates not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call panics, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_GetClientVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetClientVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetClientVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetClientVariables(ctx, req.(*GetClientVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_UpdateVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateVariables(ctx, req.(*UpdateVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_SubscribeOnUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOnUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).SubscribeOnUpdates(m, &grpc.GenericServerStream[SubscribeOnUpdatesRequest, SubscribeOnUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SubscribeOnUpdatesServer = grpc.ServerStreamingServer[SubscribeOnUpdatesResponse]

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envmn.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientVariables",
			Handler:    _ClientService_GetClientVariables_Handler,
		},
		{
			MethodName: "UpdateVariables",
			Handler:    _ClientService_UpdateVariables_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnUpdates",
			Handler:       _ClientService_SubscribeOnUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/client.proto",
}
