// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClientVariablesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	AccessKey       *string                `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3,oneof" json:"access_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetClientVariablesRequest) Reset() {
	*x = GetClientVariablesRequest{}
	mi := &file_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientVariablesRequest) ProtoMessage() {}

func (x *GetClientVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientVariablesRequest.ProtoReflect.Descriptor instead.
func (*GetClientVariablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetClientVariablesRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *GetClientVariablesRequest) GetAccessKey() string {
	if x != nil && x.AccessKey != nil {
		return *x.AccessKey
	}
	return ""
}

type GetClientVariablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     map[string]string      `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientVariablesResponse) Reset() {
	*x = GetClientVariablesResponse{}
	mi := &file_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientVariablesResponse) ProtoMessage() {}

func (x *GetClientVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientVariablesResponse.ProtoReflect.Descriptor instead.
func (*GetClientVariablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetClientVariablesResponse) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type UpdateVariablesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	AccessKey       string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Variables       map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateVariablesRequest) Reset() {
	*x = UpdateVariablesRequest{}
	mi := &file_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariablesRequest) ProtoMessage() {}

func (x *UpdateVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariablesRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVariablesRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *UpdateVariablesRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *UpdateVariablesRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type SubscribeOnUpdatesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	AccessKey       string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeOnUpdatesRequest) Reset() {
	*x = SubscribeOnUpdatesRequest{}
	mi := &file_proto_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOnUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOnUpdatesRequest) ProtoMessage() {}

func (x *SubscribeOnUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOnUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOnUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeOnUpdatesRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *SubscribeOnUpdatesRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type SubscribeOnUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOnUpdatesResponse) Reset() {
	*x = SubscribeOnUpdatesResponse{}
	mi := &file_proto_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOnUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOnUpdatesResponse) ProtoMessage() {}

func (x *SubscribeOnUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOnUpdatesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeOnUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeOnUpdatesResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_client_proto protoreflect.FileDescriptor

const file_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x12proto/client.proto\x12\x05envmn\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"\x19GetClientVariablesRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x12\"\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tH\x00R\taccessKey\x88\x01\x01B\r\n" +
	"\v_access_key\"\xaa\x01\n" +
	"\x1aGetClientVariablesResponse\x12N\n" +
	"\tvariables\x18\x01 \x03(\v20.envmn.GetClientVariablesResponse.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x16UpdateVariablesRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12J\n" +
	"\tvariables\x18\x03 \x03(\v2,.envmn.UpdateVariablesRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x19SubscribeOnUpdatesRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\".\n" +
	"\x1aSubscribeOnUpdatesResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\x91\x02\n" +
	"\rClientService\x12Y\n" +
	"\x12GetClientVariables\x12 .envmn.GetClientVariablesRequest\x1a!.envmn.GetClientVariablesResponse\x12H\n" +
	"\x0fUpdateVariables\x12\x1d.envmn.UpdateVariablesRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x12SubscribeOnUpdates\x12 .envmn.SubscribeOnUpdatesRequest\x1a!.envmn.SubscribeOnUpdatesResponse0\x01B\x11Z\x0fapi/proto;protob\x06proto3"

var (
	file_proto_client_proto_rawDescOnce sync.Once
	file_proto_client_proto_rawDescData []byte
)

func file_proto_client_proto_rawDescGZIP() []byte {
	file_proto_client_proto_rawDescOnce.Do(func() {
		file_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)))
	})
	return file_proto_client_proto_rawDescData
}

var file_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_client_proto_goTypes = []any{
	(*GetClientVariablesRequest)(nil),  // 0: envmn.GetClientVariablesRequest
	(*GetClientVariablesResponse)(nil), // 1: envmn.GetClientVariablesResponse
	(*UpdateVariablesRequest)(nil),     // 2: envmn.UpdateVariablesRequest
	(*SubscribeOnUpdatesRequest)(nil),  // 3: envmn.SubscribeOnUpdatesRequest
	(*SubscribeOnUpdatesResponse)(nil), // 4: envmn.SubscribeOnUpdatesResponse
	nil,                                // 5: envmn.GetClientVariablesResponse.VariablesEntry
	nil,                                // 6: envmn.UpdateVariablesRequest.VariablesEntry
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_proto_client_proto_depIdxs = []int32{
	5, // 0: envmn.GetClientVariablesResponse.variables:type_name -> envmn.GetClientVariablesResponse.VariablesEntry
	6, // 1: envmn.UpdateVariablesRequest.variables:type_name -> envmn.UpdateVariablesRequest.VariablesEntry
	0, // 2: envmn.ClientService.GetClientVariables:input_type -> envmn.GetClientVariablesRequest
	2, // 3: envmn.ClientService.UpdateVariables:input_type -> envmn.UpdateVariablesRequest
	3, // 4: envmn.ClientService.SubscribeOnUpdates:input_type -> envmn.SubscribeOnUpdatesRequest
	1, // 5: envmn.ClientService.GetClientVariables:output_type -> envmn.GetClientVariablesResponse
	7, // 6: envmn.ClientService.UpdateVariables:output_type -> google.protobuf.Empty
	4, // 7: envmn.ClientService.SubscribeOnUpdates:output_type -> envmn.SubscribeOnUpdatesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_client_proto_init() }
func file_proto_client_proto_init() {
	if File_proto_client_proto != nil {
		return
	}
	file_proto_client_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_proto_goTypes,
		DependencyIndexes: file_proto_client_proto_depIdxs,
		MessageInfos:      file_proto_client_proto_msgTypes,
	}.Build()
	File_proto_client_proto = out.File
	file_proto_client_proto_goTypes = nil
	file_proto_client_proto_depIdxs = nil
}
