// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/management.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_CreateEnvironment_FullMethodName             = "/envmn.management.ManagementService/CreateEnvironment"
	ManagementService_GetAllEnvironments_FullMethodName            = "/envmn.management.ManagementService/GetAllEnvironments"
	ManagementService_DeleteEnvironment_FullMethodName             = "/envmn.management.ManagementService/DeleteEnvironment"
	ManagementService_UpdateEnvironmentInfo_FullMethodName         = "/envmn.management.ManagementService/UpdateEnvironmentInfo"
	ManagementService_CreateAccessPolicy_FullMethodName            = "/envmn.management.ManagementService/CreateAccessPolicy"
	ManagementService_ListPolicyEnvironments_FullMethodName        = "/envmn.management.ManagementService/ListPolicyEnvironments"
	ManagementService_GetPolicyByName_FullMethodName               = "/envmn.management.ManagementService/GetPolicyByName"
	ManagementService_RemovePolicy_FullMethodName                  = "/envmn.management.ManagementService/RemovePolicy"
	ManagementService_AddPolicyToEnvironment_FullMethodName        = "/envmn.management.ManagementService/AddPolicyToEnvironment"
	ManagementService_RemovePolicyFromEnvironment_FullMethodName   = "/envmn.management.ManagementService/RemovePolicyFromEnvironment"
	ManagementService_UpdateEnvironmentVariables_FullMethodName    = "/envmn.management.ManagementService/UpdateEnvironmentVariables"
	ManagementService_RemoveVariableFromEnvironment_FullMethodName = "/envmn.management.ManagementService/RemoveVariableFromEnvironment"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagementServiceClient interface {
	// all requests require x-admin-password metadata
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error)
	GetAllEnvironments(ctx context.Context, in *GetAllEnvironmentsRequest, opts ...grpc.CallOption) (*GetAllEnvironmentsResponse, error)
	DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateEnvironmentInfo(ctx context.Context, in *UpdateEnvironmentInfoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateAccessPolicy(ctx context.Context, in *CreateAccessPolicyRequest, opts ...grpc.CallOption) (*CreateAccessPolicyResponse, error)
	ListPolicyEnvironments(ctx context.Context, in *ListPolicyEnvironmentsRequest, opts ...grpc.CallOption) (*ListPolicyEnvironmentsResponse, error)
	GetPolicyByName(ctx context.Context, in *GetPolicyByNameRequest, opts ...grpc.CallOption) (*GetPolicyByNameResponse, error)
	RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddPolicyToEnvironment(ctx context.Context, in *AddPolicyToEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemovePolicyFromEnvironment(ctx context.Context, in *RemovePolicyFromEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateEnvironmentVariables(ctx context.Context, in *UpdateEnvironmentVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveVariableFromEnvironment(ctx context.Context, in *RemoveVariableFromEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvironmentResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAllEnvironments(ctx context.Context, in *GetAllEnvironmentsRequest, opts ...grpc.CallOption) (*GetAllEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllEnvironmentsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAllEnvironments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_DeleteEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateEnvironmentInfo(ctx context.Context, in *UpdateEnvironmentInfoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_UpdateEnvironmentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateAccessPolicy(ctx context.Context, in *CreateAccessPolicyRequest, opts ...grpc.CallOption) (*CreateAccessPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccessPolicyResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateAccessPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListPolicyEnvironments(ctx context.Context, in *ListPolicyEnvironmentsRequest, opts ...grpc.CallOption) (*ListPolicyEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPolicyEnvironmentsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListPolicyEnvironments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetPolicyByName(ctx context.Context, in *GetPolicyByNameRequest, opts ...grpc.CallOption) (*GetPolicyByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyByNameResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetPolicyByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_RemovePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) AddPolicyToEnvironment(ctx context.Context, in *AddPolicyToEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_AddPolicyToEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemovePolicyFromEnvironment(ctx context.Context, in *RemovePolicyFromEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_RemovePolicyFromEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateEnvironmentVariables(ctx context.Context, in *UpdateEnvironmentVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_UpdateEnvironmentVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemoveVariableFromEnvironment(ctx context.Context, in *RemoveVariableFromEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_RemoveVariableFromEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
type ManagementServiceServer interface {
	// all requests require x-admin-password metadata
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error)
	GetAllEnvironments(context.Context, *GetAllEnvironmentsRequest) (*GetAllEnvironmentsResponse, error)
	DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*emptypb.Empty, error)
	UpdateEnvironmentInfo(context.Context, *UpdateEnvironmentInfoRequest) (*emptypb.Empty, error)
	CreateAccessPolicy(context.Context, *CreateAccessPolicyRequest) (*CreateAccessPolicyResponse, error)
	ListPolicyEnvironments(context.Context, *ListPolicyEnvironmentsRequest) (*ListPolicyEnvironmentsResponse, error)
	GetPolicyByName(context.Context, *GetPolicyByNameRequest) (*GetPolicyByNameResponse, error)
	RemovePolicy(context.Context, *RemovePolicyRequest) (*emptypb.Empty, error)
	AddPolicyToEnvironment(context.Context, *AddPolicyToEnvironmentRequest) (*emptypb.Empty, error)
	RemovePolicyFromEnvironment(context.Context, *RemovePolicyFromEnvironmentRequest) (*emptypb.Empty, error)
	UpdateEnvironmentVariables(context.Context, *UpdateEnvironmentVariablesRequest) (*emptypb.Empty, error)
	RemoveVariableFromEnvironment(context.Context, *RemoveVariableFromEnvironmentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedManagementServiceServer) GetAllEnvironments(context.Context, *GetAllEnvironmentsRequest) (*GetAllEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllEnvironments not implemented")
}
func (UnimplementedManagementServiceServer) DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnvironment not implemented")
}
func (UnimplementedManagementServiceServer) UpdateEnvironmentInfo(context.Context, *UpdateEnvironmentInfoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvironmentInfo not implemented")
}
func (UnimplementedManagementServiceServer) CreateAccessPolicy(context.Context, *CreateAccessPolicyRequest) (*CreateAccessPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccessPolicy not implemented")
}
func (UnimplementedManagementServiceServer) ListPolicyEnvironments(context.Context, *ListPolicyEnvironmentsRequest) (*ListPolicyEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicyEnvironments not implemented")
}
func (UnimplementedManagementServiceServer) GetPolicyByName(context.Context, *GetPolicyByNameRequest) (*GetPolicyByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicyByName not implemented")
}
func (UnimplementedManagementServiceServer) RemovePolicy(context.Context, *RemovePolicyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePolicy not implemented")
}
func (UnimplementedManagementServiceServer) AddPolicyToEnvironment(context.Context, *AddPolicyToEnvironmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPolicyToEnvironment not implemented")
}
func (UnimplementedManagementServiceServer) RemovePolicyFromEnvironment(context.Context, *RemovePolicyFromEnvironmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePolicyFromEnvironment not implemented")
}
func (UnimplementedManagementServiceServer) UpdateEnvironmentVariables(context.Context, *UpdateEnvironmentVariablesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvironmentVariables not implemented")
}
func (UnimplementedManagementServiceServer) RemoveVariableFromEnvironment(context.Context, *RemoveVariableFromEnvironmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVariableFromEnvironment not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAllEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAllEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAllEnvironments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAllEnvironments(ctx, req.(*GetAllEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeleteEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteEnvironment(ctx, req.(*DeleteEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateEnvironmentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvironmentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateEnvironmentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateEnvironmentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateEnvironmentInfo(ctx, req.(*UpdateEnvironmentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateAccessPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateAccessPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateAccessPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateAccessPolicy(ctx, req.(*CreateAccessPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListPolicyEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPolicyEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListPolicyEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListPolicyEnvironments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListPolicyEnvironments(ctx, req.(*ListPolicyEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetPolicyByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetPolicyByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetPolicyByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetPolicyByName(ctx, req.(*GetPolicyByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemovePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemovePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemovePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemovePolicy(ctx, req.(*RemovePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_AddPolicyToEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPolicyToEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).AddPolicyToEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_AddPolicyToEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).AddPolicyToEnvironment(ctx, req.(*AddPolicyToEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemovePolicyFromEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePolicyFromEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemovePolicyFromEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemovePolicyFromEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemovePolicyFromEnvironment(ctx, req.(*RemovePolicyFromEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateEnvironmentVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvironmentVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateEnvironmentVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateEnvironmentVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateEnvironmentVariables(ctx, req.(*UpdateEnvironmentVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemoveVariableFromEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVariableFromEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemoveVariableFromEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemoveVariableFromEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemoveVariableFromEnvironment(ctx, req.(*RemoveVariableFromEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envmn.management.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnvironment",
			Handler:    _ManagementService_CreateEnvironment_Handler,
		},
		{
			MethodName: "GetAllEnvironments",
			Handler:    _ManagementService_GetAllEnvironments_Handler,
		},
		{
			MethodName: "DeleteEnvironment",
			Handler:    _ManagementService_DeleteEnvironment_Handler,
		},
		{
			MethodName: "UpdateEnvironmentInfo",
			Handler:    _ManagementService_UpdateEnvironmentInfo_Handler,
		},
		{
			MethodName: "CreateAccessPolicy",
			Handler:    _ManagementService_CreateAccessPolicy_Handler,
		},
		{
			MethodName: "ListPolicyEnvironments",
			Handler:    _ManagementService_ListPolicyEnvironments_Handler,
		},
		{
			MethodName: "GetPolicyByName",
			Handler:    _ManagementService_GetPolicyByName_Handler,
		},
		{
			MethodName: "RemovePolicy",
			Handler:    _ManagementService_RemovePolicy_Handler,
		},
		{
			MethodName: "AddPolicyToEnvironment",
			Handler:    _ManagementService_AddPolicyToEnvironment_Handler,
		},
		{
			MethodName: "RemovePolicyFromEnvironment",
			Handler:    _ManagementService_RemovePolicyFromEnvironment_Handler,
		},
		{
			MethodName: "UpdateEnvironmentVariables",
			Handler:    _ManagementService_UpdateEnvironmentVariables_Handler,
		},
		{
			MethodName: "RemoveVariableFromEnvironment",
			Handler:    _ManagementService_RemoveVariableFromEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/management.proto",
}
