// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :exec
INSERT INTO environments (id, name, description, last_variables_update, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEnvironmentParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	Name                string    `db:"name" json:"name"`
	Description         *string   `db:"description" json:"description"`
	LastVariablesUpdate time.Time `db:"last_variables_update" json:"last_variables_update"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createEnvironment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LastVariablesUpdate,
		arg.CreatedAt,
	)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, name, description, last_variables_update, created_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LastVariablesUpdate,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT id, name, description, last_variables_update, created_at FROM environments WHERE name = $1
`

func (q *Queries) GetEnvironmentByName(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LastVariablesUpdate,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, description, last_variables_update, created_at FROM environments
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LastVariablesUpdate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
