// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type AccessPolicy struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Key       string    `db:"key" json:"key"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Environment struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	Name                string    `db:"name" json:"name"`
	Description         *string   `db:"description" json:"description"`
	LastVariablesUpdate time.Time `db:"last_variables_update" json:"last_variables_update"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
}

type EnvironmentsAccessPolicy struct {
	AccessPolicyID uuid.UUID `db:"access_policy_id" json:"access_policy_id"`
	EnvironmentID  uuid.UUID `db:"environment_id" json:"environment_id"`
	ChangesAllowed bool      `db:"changes_allowed" json:"changes_allowed"`
}

type Variable struct {
	ID            int32     `db:"id" json:"id"`
	Key           string    `db:"key" json:"key"`
	Value         string    `db:"value" json:"value"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}
