// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variables.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM variables WHERE environment_id = $1 AND key = $2
`

type DeleteVariableParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Key           string    `db:"key" json:"key"`
}

func (q *Queries) DeleteVariable(ctx context.Context, arg DeleteVariableParams) error {
	_, err := q.db.Exec(ctx, deleteVariable, arg.EnvironmentID, arg.Key)
	return err
}

const getVariablesByEnv = `-- name: GetVariablesByEnv :many
SELECT key, value FROM variables WHERE environment_id = $1
`

type GetVariablesByEnvRow struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) GetVariablesByEnv(ctx context.Context, environmentID uuid.UUID) ([]GetVariablesByEnvRow, error) {
	rows, err := q.db.Query(ctx, getVariablesByEnv, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariablesByEnvRow
	for rows.Next() {
		var i GetVariablesByEnvRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVariable = `-- name: UpsertVariable :exec
INSERT INTO variables (key, value, environment_id)
VALUES ($1, $2, $3)
ON CONFLICT (key, environment_id)
DO UPDATE SET value = EXCLUDED.value
`

type UpsertVariableParams struct {
	Key           string    `db:"key" json:"key"`
	Value         string    `db:"value" json:"value"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) UpsertVariable(ctx context.Context, arg UpsertVariableParams) error {
	_, err := q.db.Exec(ctx, upsertVariable, arg.Key, arg.Value, arg.EnvironmentID)
	return err
}
